                               02Dragora
                       04https://www.dragora.org07


BOOT PARAMETERS

The following variables are boot parameters for the live system startup.
Any parameters given on the command line will only be valid for the
current session.

Defaults for the options are specified in brackets.

RC_HWCLOCK=08.......... 07Set hardware clock timescale, 0futc07 or 0flocal07 [03utc07]
RC_HOSTNAME=08......... 07Set system host name [03dragora07]
RC_DOMAINNAME=08....... 07Set system domain name [03example.net07]
RC_ESPEAKUP=08......... 07Use 03on07 to enable eSpeakup (software synthesizer) [03off07]
RC_ESPEAKUP_VOICE=08... 07Voice for the software synthesizer [03default07]
RC_KEYMAP=08........... 07Keyboard map for the console [03qwerty/us07]
RC_BLANKTIME=08........ 07Terminal screen blanking in minutes [031507]


... press [Enter] or [Esc] to return.
