                               02Dragora
                       08http://www.dragora.org07

Boot options:

Defaults for the options are specified in brackets.

RC_HWCLOCK=09.......... 07Set hardware clock timescale, 0futc07 or 0flocal07 [09utc07]
RC_HOSTNAME=09......... 07Set system host name [09dragora07]
RC_DOMAINNAME=09....... 07Set system domain name [09example.net07]
RC_ESPEAKUP=09......... 07Use 0f107 to enable eSpeakup (software synthesizer) [09007]
RC_EVOICE=09........... 07Voice for the software synthesizer [09default07]
RC_KEYMAP=09........... 07Keyboard map for the console [09qwerty/us07]
RC_BLANKTIME=09........ 07Terminal screen blanking in minutes [091507]

These are boot parameters for the distribution's startup.  Any passed
command-line parameter is only valid for the current session.  If you
wish to make a permanent change after booting, please refer to the
distribution documentation.

0fIMPORTANT! Default login password for "root" is: dragora07

    To continue, press [Enter] or [Esc].
