#! /bin/sh -
#
# Dragora installer
#
# Copyright (c) 2019 Matias Fonzo, <selk@dragora.org>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Exit immediately on any error
set -e

PROGRAM="${0##*/}"
TMPDIR="${TMPDIR:-$HOME}"
TMPFILE="${TMPDIR}/${PROGRAM}.${RANDOM-0}$$"
LOCKFILE=/tmp/dragora-installer.lockfile

# Override locale settings
LC_ALL=C
LANGUAGE=C
export LC_ALL LANGUAGE

chkstatus_or_exit()
{
    status=$?

    echo ""

    # Clean up temporary files
    rm -f -- "$TMPFILE" "$LOCKFILE"

    # Clean up temporary subdirectory related to the installer
    test -d "$SUBTMPDIR" && rm -rf -- "$SUBTMPDIR"

    if test $status -ne 0
    then
        echo "Return status = $status" 1>&2
        exit 2;
    fi

    unset status
}

# Sanity checks

if test ! -d "$TMPDIR"
then
    echo "${PROGRAM}: \`${TMPDIR}' is not a qualified temporary directory" 1>&2
    exit 1;
fi
if test ! -w "$TMPDIR"
then
    echo "${PROGRAM}: \`${TMPDIR}' is not a writable temporary directory" 1>&2
    exit 1;
fi

trap 'chkstatus_or_exit' EXIT HUP INT QUIT ABRT TERM

umask 077;	# Remove access for all but user.

# Set a lock to allow only one instance of the installer

if ( set -C ; echo ": $PROGRAM - locked" > $LOCKFILE ) 2> /dev/null
then
    true
else
    if test -e "$LOCKFILE"
    then
        echo "Only one instance of \`${PROGRAM}' is allowed." 1>&2
        exit 1;
    else
        echo "${PROGRAM}: \`${LOCKFILE}' lock failed." 1>&2
        exit 2;
    fi
fi

# Create subdirectory to store the files produced by the installer

SUBTMPDIR="${TMPDIR}/.${PROGRAM}"	# Default sets to "${HOME}/.dragora-installer".
mkdir -p -m 700 -- $SUBTMPDIR

umask 022;	# Remove write permission for group and other.

# Detect and prepare initial list of Linux partition(s)

if fdisk -l | grep -q -m 1 Linux
then
    fdisk -l | grep Linux | LC_COLLATE=C sort > ${SUBTMPDIR}/partitions
else
    printf "%s\n" \
     "    Linux partitions were not detected."                               \
     ""                                                                      \
     "A Linux partition is required to continue the installation.  You can"  \
     "use utilities such as fdisk(8), cfdisk(8) or parted(8) to create at"   \
     "least one Linux partition.  Then run \`${PROGRAM}' again."             \
     ""
     exit 1;
fi

# Determine the maximum size of the terminal to be used on the dialogues.
# Try using shell variables that set LINES and COLUMNS, first.
echo "Checking terminal size ..."
if test -z "$LINES"
then
    LINES="$(tput lines)" || \
     { LINES="$(stty size)" && LINES="${LINES% *}"; }
fi
if test -z "$COLUMNS"
then
    COLUMNS="$(tput cols)" || \
     { COLUMNS="$(stty size)" && COLUMNS="${COLUMNS#* }"; }
fi
echo "$LINES $COLUMNS"

export SUBTMPDIR LINES COLUMNS

dialog --colors \
 --backtitle "\ZbDragora 3.0 Installer" \
 --hfile "@PARTS@HELP_F1" \
 --title "INSTALLER INFORMATION" \
 --msgbox \
"Welcome to \Z3${PROGRAM}\Zn.\n\n\
This program prepares Dragora 3.0 to run on your computer.\n\n\
    - To set up Dragora now, press \Zb\Z7ENTER\Zn.\n\n\
    - To quit, press \Zb\Z7ESC\Zn.\n\n\
Please read the installer's help before proceeding (\Zb\Z7F1\Zn)." 14 63

# Try to detect and mount the hybrid ISO image, there may be a USB memory
# stick already inserted.  If not, the media menu will be displayed.

mkdir -p -- /media/dragora-medium

if ! blkid -t LABEL="Dragora Packages" 2> /dev/null
then
    dialog --colors \
     --backtitle "\ZbInstallation Medium" \
     --title "Pendrive/SDCard/CDROM" \
     --msgbox \
"Please insert the media labeled as \"Dragora Packages\" and\n\
press \Zb\Z7ENTER\Zn to continue.  Otherwise a media selection menu\n\
will be displayed." 7 63
    if blkid -t LABEL="Dragora Packages" 2> /dev/null
    then
        mount -t iso9660 LABEL="Dragora Packages" /media/dragora-medium 2> /dev/null
        echo "/media/dragora-medium/packages" > ${SUBTMPDIR}/MediumFound
    else
        . @PARTS@MenuMedia
    fi
fi

# Clean up possible empty mount-directories
rmdir -- \
 /media/dragora-medium \
 /media/dragora-root 2> /dev/null || true

# Double-check to see the installation directory
if test ! -f "${SUBTMPDIR}/MediumFound"
then
    dialog --colors \
     --backtitle "\ZbInstallation Medium" \
     --title "MEDIUM NOT FOUND" \
     --sleep 7 --infobox \
"\nNo means of installation was found to proceed with\n\
the installation of Dragora.  Please check your\n\
drives and the directory containing the software\n\
packages." 8 55
    exit 99;
fi

. @PARTS@MakeSwap	# Verify/give format to a Swap partition.
. @PARTS@MakeFS		# Verify/give format to Linux partitions.
. @PARTS@FstabEdit	# File system table edition (fstab).
. @PARTS@MountRoot	# Mount root partition for installation.
. @PARTS@FstabMounts	# Mount rest of partitions from fstab.

