\input texinfo   @c -*-texinfo-*-
@comment $Id@w{$}
@comment %**start of header
@setfilename qi.info
@settitle Qi user guide
@documentencoding ISO-8859-1
@syncodeindex pg cp
@comment %**end of header

@set VERSION 2.10-rc6
@set UPDATED 15 Aug 2022

@dircategory Package management
@direntry
* Qi: (qi).                   A user-friendly package manager.
@end direntry


@ifnothtml
@titlepage
@finalout
@title Qi
@subtitle for version @value{VERSION}, @value{UPDATED}
@author Matias Fonzo (@email{selk@@dragora.org})

@page
@vskip 0pt plus 1filll
@end titlepage

@contents
@end ifnothtml

@ifnottex
@node Top
@top

This user guide is for Qi (version @value{VERSION},
@value{UPDATED}).
@end ifnottex

@menu
* Introduction to Qi::        Description and features of qi
* Invoking qi::               Command-line options
* The qirc file::             Configuration file
* Packages::                  Managing packages
* Recipes::                   Building packages
* Order files::               Handling build order
* Creating packages::         Making Qi packages
* Examining packages::        Debugging purposes
* Qi exit status::            Exit codes
* Index::
@end menu

@sp 1
Copyright @copyright{} 2019-2022 Matias Andres Fonzo, Santiago del Estero,
Argentina.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

@include qi-content.texi

@node Index
@unnumbered Index

@printindex cp

@bye

