#! /bin/sh

set -e
set -x

rm -rf html_node
mkdir html_node

htmldoc -t html -d html_node \
 --no-title \
 --toclevels 2 \
 --toctitle "Dragora Documentation" \
 ./about.html ./installation.html ./configuration.html \
 ./pkgmanagement.html

# Adjust main title

sed -i \
 's#<TITLE>Qi user guide</TITLE>#<TITLE>Dragora Documentation</TITLE>#' \
 ./html_node/index.html

