--- Makefile_original	2014-04-18 17:35:39.000000000 +0000
+++ Makefile	2018-10-10 05:02:25.291859058 +0000
@@ -24,13 +24,13 @@
 TREE_DEST=tree
 BINDIR=${prefix}/bin
 MAN=tree.1
-MANDIR=${prefix}/man/man1
+MANDIR=${prefix}/share/man/man1
 OBJS=tree.o unix.o html.o xml.o json.o hash.o color.o
 
 # Uncomment options below for your particular OS:
 
 # Linux defaults:
-CFLAGS=-ggdb -Wall -DLINUX -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
+CFLAGS=-g0 -Os -march=i586 -mtune=i686
 #CFLAGS=-O4 -Wall  -DLINUX -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
 #LDFLAGS=-s
 
