#! /bin/sh -
#
# Turn shadow passwords on or off (based on Debian's shadowconfig.sh)
#
# Copyright (c) 2018 Matias Fonzo, <selk@dragora.org>.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

umask 022
IFS='
 	'
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin

# Exit immediately on any error
set -e

usage()
{
    echo "Usage: ${0##*/} [on|off]"
    echo "Turn shadow passwords ON or OFF."
}

# Show the help when there are no arguments
if test $# -eq 0
then
    usage
    exit 0
fi

# Be immune to the following signals
trap "" HUP INT QUIT ABRT TERM

# Parse options

case $1 in
    on | ON )
        pwck -q -r
        grpck -r
        pwconv
        grpconv
        chown root:root /etc/passwd /etc/group
        chmod 644 /etc/passwd /etc/group
        chown root:shadow /etc/shadow /etc/gshadow
        chmod 640 /etc/shadow /etc/gshadow
        ;;
    off | OFF )
        pwck -q -r
        grpck -r
        pwunconv
        grpunconv
        # sometimes the passwd perms get munged
        chown root:root /etc/passwd /etc/group
        chmod 644 /etc/passwd /etc/group
        ;;
    *)
        usage
        exit 1
        ;;
esac

