#! /bin/sh -
#
# /etc/cron.daily/man-db - Update manual page(s) database periodically.
#

set -e
umask 022

# Unset man path, otherwise the configuration file is ignored
test -n "${MANPATH+$MANPATH}" && unset MANPATH

test -d /var/cache/man || mkdir -p /var/cache/man
ionice -c 3 nice -n 14 mandb --quiet 2> /dev/null

