#! /bin/sh -
#
# /etc/cron.daily/man-db - Update manual page(s) database periodically.
#

set -e
umask 022

# Unset $MANPATH to read from configuration file
if test -f /etc/man_db.conf
then
    unset MANPATH
fi

test -d /var/cache/man || mkdir -p /var/cache/man
ionice -c 3 nice -n 14 mandb --quiet 2> /dev/null

