#! /bin/sh -
#
# Script borrowed from Fedora, slightly adapted
# for Dragora GNU/Linux-Libre.
#
default_flag="-std=c99"

for option in "$@"
do
    case $option in
    -std=c99 | -std=c9x | -std=iso9899:1999 | -std=iso9899:199x )
        default_flag=""
        ;;
    -std=*)
        echo "`basename -- "$0"` called with non ISO C99 option $option" 1>&2
        exit 1
        ;;
    esac
done

exec gcc $default_flag ${1+"$@"}

